import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_URL = "https://raw.githubusercontent.com/AIsouler/MyClash/main/Script/Script.js";
const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(rootDir, "src", "vendor", "myclash-script.ts");

const response = await fetch(SOURCE_URL, {
  headers: { "user-agent": "clash-fusion-sync/1.0" },
});

if (!response.ok) {
  throw new Error(`Failed to download MyClash Script.js: ${response.status} ${response.statusText}`);
}

const source = await response.text();

if (!source.includes("function main(config)")) {
  throw new Error("Unexpected MyClash Script.js format: main(config) was not found");
}

function replaceRequired(input, search, replacement) {
  if (!input.includes(search)) {
    throw new Error(`Unexpected MyClash Script.js format: missing transform anchor: ${search.slice(0, 80)}`);
  }
  return input.replace(search, replacement);
}

const header = `// This file is generated by scripts/sync-myclash.mjs.
// Source: ${SOURCE_URL}
// Do not edit generated MyClash logic by hand; rerun \`pnpm sync:myclash\` and review the diff.

export interface MyClashProxy {
  name: string;
  type?: unknown;
  server?: unknown;
  port?: unknown;
  [key: string]: unknown;
}

export interface MyClashConfig {
  proxies?: MyClashProxy[];
  dns?: Record<string, unknown>;
  hosts?: Record<string, unknown>;
  [key: string]: unknown;
}

type MyClashProxyGroup = Record<string, unknown> & {
  name: string;
  type?: string;
  proxies?: string[];
};

interface RegionDefinition {
  name: string;
  regex: RegExp;
  icon: string;
}

interface ServiceConfig {
  name: string;
  defaultSelected?: string;
  providers?: Record<string, unknown>;
  icon: string;
  rules: string[];
  direct?: boolean;
  reject?: boolean;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function asStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.map((item) => String(item)) : [];
}

`;

let transformed = source;
transformed = replaceRequired(transformed, "// ------- AIsouler自用脚本 -------\n\n", "");
transformed = replaceRequired(transformed, "const regionDefinitions = [", "const regionDefinitions: RegionDefinition[] = [");
transformed = replaceRequired(transformed, "const serviceConfigs = [", "const serviceConfigs: ServiceConfig[] = [");
transformed = replaceRequired(
  transformed,
    "function createRegionGroup(name, icon, proxies) {",
    "function createRegionGroup(name: string, icon: string, proxies: string[]): MyClashProxyGroup[] {",
);
transformed = replaceRequired(transformed, "function main(config) {", "export function main(config: MyClashConfig): MyClashConfig {");
transformed = replaceRequired(transformed, "  const newConfig = {};", "  const newConfig: MyClashConfig = {};");
transformed = replaceRequired(
  transformed,
    "  const regionGroups = Object.fromEntries(regionDefinitions.map((r) => [r.name, { ...r, proxies: [] }]));",
    "  const regionGroups: Record<string, RegionDefinition & { proxies: string[] }> = Object.fromEntries(regionDefinitions.map((r) => [r.name, { ...r, proxies: [] as string[] }]));",
);
transformed = replaceRequired(transformed, "  const otherProxies = [];", "  const otherProxies: string[] = [];");
transformed = replaceRequired(transformed, "  const functionalGroups = [];", "  const functionalGroups: MyClashProxyGroup[] = [];");
transformed = replaceRequired(
  transformed,
    "  const finalRuleProviders = { ...baseRuleProviders };",
    "  const finalRuleProviders: Record<string, unknown> = { ...baseRuleProviders };",
);
transformed = replaceRequired(
  transformed,
    "    filteredProxies.filter((proxy) => typeof proxy.server === 'string').map((proxy) => proxy.server.toLowerCase()),",
    "    filteredProxies.flatMap((proxy) => typeof proxy.server === 'string' ? [proxy.server.toLowerCase()] : []),",
);
transformed = replaceRequired(transformed, "  const originalDnsConfig = config.dns || {};", "  const originalDnsConfig = asRecord(config.dns);");
transformed = replaceRequired(
  transformed,
    "  const originalProxyServerNameserver = (originalDnsConfig['proxy-server-nameserver'] || []).filter(\n    (dns) => !commonDnsRegex.test(String(dns)),\n  );",
    "  const originalProxyServerNameserver = asStringArray(originalDnsConfig['proxy-server-nameserver']).filter(\n    (dns) => !commonDnsRegex.test(dns),\n  );",
);
transformed = replaceRequired(
  transformed,
    "    originalDnsConfig['nameserver-policy'] || {},\n    originalDnsConfig['proxy-server-nameserver-policy'] || {},",
    "    asRecord(originalDnsConfig['nameserver-policy']),\n    asRecord(originalDnsConfig['proxy-server-nameserver-policy']),",
);
transformed = replaceRequired(transformed, "  const originalPolicyNameserver = {};", "  const originalPolicyNameserver: Record<string, unknown> = {};");
transformed = replaceRequired(transformed, "  const originalHosts = config.hosts || {};", "  const originalHosts = asRecord(config.hosts);");
transformed = replaceRequired(transformed, "  const proxyHosts = {};", "  const proxyHosts: Record<string, unknown> = {};");

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, header + transformed, "utf8");

console.log(`Synced MyClash Script.js to ${outputPath}`);
