export const TEMPLATE: Record<string, unknown> = {
  dns: {
    enable: true,
    ipv6: false,
    "enhanced-mode": "fake-ip",
    "default-nameserver": ["119.29.29.29", "223.5.5.5"],
    "nameserver-policy": {
      "geosite:cn,private,apple": ["https://doh.pub/dns-query", "https://dns.alidns.com/dns-query"],
      "*.linux.do": "https://xxx.ddd.oaifree.com/query-dns",
      "linux.do": "https://xxx.ddd.oaifree.com/query-dns",
    },
    nameserver: ["https://1.1.1.1/dns-query#🚀 节点选择", "https://8.8.8.8/dns-query#🚀 节点选择"],
    "proxy-server-nameserver": ["119.29.29.29", "223.5.5.5"],
    "direct-nameserver": ["https://doh.pub/dns-query", "https://dns.alidns.com/dns-query"],
    "direct-nameserver-follow-policy": true,
    "fake-ip-range": "198.18.0.0/16",
    "fake-ip-filter": [
      "*.lan", "*.local", "*.arpa", "time.*.com", "ntp.*.com",
      "+.market.xiaomi.com", "localhost.ptlogin2.qq.com",
      "*.msftncsi.com", "www.msftconnecttest.com",
    ],
  },
  "proxy-groups": [
    { name: "🚀 节点选择", type: "select", proxies: ["♻️ 自动选择", "DIRECT"] },
    { name: "♻️ 自动选择", type: "url-test", proxies: ["$all"], url: "https://www.gstatic.com/generate_204", interval: 300 },
    { name: "📲 电报消息", type: "select", proxies: ["🚀 节点选择", "♻️ 自动选择", "DIRECT"] },
    { name: "🐧 Linux.do", type: "select", proxies: ["🚀 节点选择", "♻️ 自动选择", "DIRECT"] },
    { name: "🎯 全球直连", type: "select", proxies: ["DIRECT", "🚀 节点选择"] },
  ],
  "rule-providers": {
    Telegram: {
      type: "http",
      behavior: "classical",
      url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram_No_Resolve.yaml",
      format: "yaml",
      path: "./ruleset/Telegram.yaml",
      interval: 86400,
    },
    Apple: {
      type: "http",
      behavior: "classical",
      url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Apple.yaml",
      format: "yaml",
      path: "./ruleset/Apple.yaml",
      interval: 86400,
    },
    AllProxy: {
      type: "http",
      behavior: "domain",
      url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global_Domain.yaml",
      format: "yaml",
      path: "./ruleset/AllProxy.yaml",
      interval: 86400,
    },
  },
  rules: [
    "GEOSITE,private,DIRECT",
    "GEOIP,private,DIRECT,no-resolve",
    "RULE-SET,Telegram,📲 电报消息",
    "RULE-SET,Apple,🎯 全球直连",
    "DOMAIN-SUFFIX,linux.do,🐧 Linux.do",
    "GEOSITE,CN,🎯 全球直连",
    "RULE-SET,AllProxy,🚀 节点选择",
    "GEOIP,CN,🎯 全球直连",
    "MATCH,🚀 节点选择",
  ],
};
