export const TEMPLATE: Record<string, unknown> = {
  dns: {
    enable: true,
    ipv6: false,
    "enhanced-mode": "fake-ip",
    "default-nameserver": ["119.29.29.29", "223.5.5.5"],
    "nameserver-policy": {
      "geosite:cn,private,apple": ["https://doh.pub/dns-query", "https://dns.alidns.com/dns-query"],
    },
    nameserver: ["https://1.1.1.1/dns-query#RULES", "https://8.8.8.8/dns-query#RULES"],
    "proxy-server-nameserver": ["119.29.29.29", "223.5.5.5"],
    "direct-nameserver": ["https://doh.pub/dns-query", "https://dns.alidns.com/dns-query"],
    "direct-nameserver-follow-policy": true,
    "fake-ip-range": "198.18.0.0/16",
    "fake-ip-filter": [
      "*.lan", "*.local", "*.arpa", "time.*.com", "ntp.*.com",
      "+.market.xiaomi.com", "localhost.ptlogin2.qq.com",
      "*.msftncsi.com", "www.msftconnecttest.com",
    ],
  },
  proxies: [
    {
      name: "🏢 aTrust-Docker",
      type: "socks5",
      server: "127.0.0.1",
      port: 1080,
      "skip-cert-verify": true,
      udp: true,
    },
  ],
  "proxy-groups": [
    { name: "🚀 节点选择", type: "select", proxies: ["$all", "DIRECT"] },
    { name: "📲 电报消息", type: "select", proxies: ["🚀 节点选择", "DIRECT"] },
    { name: "🎯 全球直连", type: "select", proxies: ["DIRECT", "🚀 节点选择"] },
    { name: "🏢 aTrust", type: "select", proxies: ["🏢 aTrust-Docker", "DIRECT"] },
  ],
  "rule-providers": {
    Telegram: {
      type: "http",
      behavior: "classical",
      url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram_No_Resolve.yaml",
      format: "yaml",
      path: "./ruleset/Telegram.yaml",
      interval: 86400,
    },
    Apple: {
      type: "http",
      behavior: "classical",
      url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Apple.yaml",
      format: "yaml",
      path: "./ruleset/Apple.yaml",
      interval: 86400,
    },
    AllProxy: {
      type: "http",
      behavior: "domain",
      url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global_Domain.yaml",
      format: "yaml",
      path: "./ruleset/AllProxy.yaml",
      interval: 86400,
    },
  },
  rules: [
    // 防回环：aTrust 容器（经 OrbStack 发出）访问内网时不能再送回 aTrust 自身
    "AND,((PROCESS-NAME,OrbStack Helper),(IP-CIDR,10.239.36.1/32,no-resolve)),DIRECT",
    "IP-CIDR,10.239.36.1/32,🏢 aTrust,no-resolve",
    "GEOSITE,private,DIRECT",
    "GEOIP,private,DIRECT,no-resolve",
    "RULE-SET,Telegram,📲 电报消息",
    "RULE-SET,Apple,🎯 全球直连",
    "DOMAIN-SUFFIX,linux.do,🚀 节点选择",
    "GEOSITE,CN,🎯 全球直连",
    "RULE-SET,AllProxy,🚀 节点选择",
    "GEOIP,CN,🎯 全球直连",
    "MATCH,🚀 节点选择",
  ],
};
