import { stringify } from "yaml";
import { main as buildMyClashConfig } from "./vendor/myclash-script";
import { parseSubscriptionConfig } from "./proxy-parser";
import { dedupeByEndpoint, ensureUniqueProxyNames, sortByName, excludeByName } from "./filters";
import type { ClashProxy, ParsedSubscription } from "./proxy-parser";
import type { MyClashConfig, MyClashProxy } from "./vendor/myclash-script";

export interface Env {
  AUTH_TOKEN?: string;
  SUBSCRIPTION_URLS?: string;
  EXCLUDE_PATTERN?: string;
}

const YAML_STRINGIFY_OPTIONS = {
  lineWidth: 0,
};

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/config.yaml" || url.pathname === "/") {
      const token = url.searchParams.get("token") || request.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
      if (env.AUTH_TOKEN && token !== env.AUTH_TOKEN) {
        return new Response("Unauthorized", { status: 401 });
      }

      const subscriptionUrls = (env.SUBSCRIPTION_URLS || "")
        .split("\n")
        .map((s) => s.trim())
        .filter(Boolean);

      if (subscriptionUrls.length === 0) {
        return new Response("SUBSCRIPTION_URLS secret is not configured", { status: 500 });
      }

      let excludePattern: RegExp | null = null;
      if (env.EXCLUDE_PATTERN) {
        try {
          excludePattern = new RegExp(env.EXCLUDE_PATTERN);
        } catch (e) {
          return new Response(`Invalid EXCLUDE_PATTERN: ${e instanceof Error ? e.message : String(e)}`, { status: 400 });
        }
      }

      try {
        const results = await Promise.allSettled(
          subscriptionUrls.map((subUrl) => fetchSubscription(subUrl)),
        );

        const allProxies: ClashProxy[] = [];
        const sourceDns: Record<string, unknown> = {};
        const sourceHosts: Record<string, unknown> = {};
        let failedCount = 0;
        for (const result of results) {
          if (result.status === "fulfilled") {
            allProxies.push(...result.value.proxies);
            mergeRecord(sourceDns, result.value.dns);
            mergeRecord(sourceHosts, result.value.hosts);
          } else {
            failedCount += 1;
            console.warn(`Subscription fetch failed: ${result.reason instanceof Error ? result.reason.message : String(result.reason)}`);
          }
        }

        let processed = allProxies;
        if (excludePattern) {
          processed = excludeByName(processed, excludePattern);
        }
        processed = dedupeByEndpoint(processed);
        processed = ensureUniqueProxyNames(processed);
        processed = sortByName(processed);

        if (processed.length === 0) {
          return new Response(
            `No proxies available after parsing/filtering. subscriptions=${subscriptionUrls.length}, failed=${failedCount}, parsed=${allProxies.length}`,
            { status: 502 },
          );
        }

        const cleanProxies: MyClashProxy[] = processed.map(({ name, type, server, port, ...rest }) => {
          const obj: MyClashProxy = { name, type, server, port };
          for (const [k, v] of Object.entries(rest)) {
            if (v !== undefined && v !== null && v !== "") obj[k] = v;
          }
          return obj;
        });

        const sourceConfig: MyClashConfig = {
          proxies: cleanProxies,
          ...(Object.keys(sourceDns).length > 0 ? { dns: sourceDns } : {}),
          ...(Object.keys(sourceHosts).length > 0 ? { hosts: sourceHosts } : {}),
        };
        const config = buildMyClashConfig(sourceConfig);

        const header = `# Generated by clash-fusion using vendored MyClash Script.js\n# Nodes: ${processed.length}\n`;
        const body = quoteBareHashListItems(stringify(config, YAML_STRINGIFY_OPTIONS));
        return new Response(header + body, {
          headers: {
            "content-type": "text/yaml; charset=utf-8",
            "profile-update-interval": "6",
            "cache-control": "no-store",
          },
        });
      } catch (e) {
        return new Response(`Error: ${e instanceof Error ? e.message : String(e)}`, { status: 500 });
      }
    }

    return new Response("Not Found", { status: 404 });
  },
};

async function fetchSubscription(subUrl: string): Promise<ParsedSubscription> {
  const resp = await fetch(subUrl, {
    headers: { "user-agent": "clash-verge/2.0" },
    signal: AbortSignal.timeout(30000),
  });
  if (!resp.ok) {
    console.warn(`Failed ${subUrl.slice(0, 60)}: ${resp.status}`);
    return { proxies: [] };
  }
  const text = await resp.text();
  if (!text.trim()) return { proxies: [] };
  return parseSubscriptionConfig(text);
}

function mergeRecord(target: Record<string, unknown>, source: Record<string, unknown> | undefined): void {
  if (!source) return;
  for (const [key, value] of Object.entries(source)) {
    const existing = target[key];
    if (isPlainRecord(existing) && isPlainRecord(value)) {
      mergeRecord(existing, value);
    } else {
      target[key] = value;
    }
  }
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function quoteBareHashListItems(yaml: string): string {
  return yaml.split("\n").map((line) => {
    const match = line.match(/^(\s*-\s+)([^"'[{].*#.*)$/);
    if (!match) return line;

    const [, prefix, rawValue] = match;
    const value = rawValue.trimEnd();

    // Keep ordinary YAML comments such as: - item # comment
    if (/\s#/.test(value)) return line;

    return `${prefix}${JSON.stringify(value)}`;
  }).join("\n");
}
