import { stringify } from "yaml";
import { TEMPLATE } from "./config";
import { parseSubscriptionContent } from "./proxy-parser";
import { dedupeByEndpoint, sortByName, excludeByName } from "./filters";
import type { ClashProxy } from "./proxy-parser";

export interface Env {
  AUTH_TOKEN?: string;
  SUBSCRIPTION_URLS?: string;
  EXCLUDE_PATTERN?: string;
}

const YAML_STRINGIFY_OPTIONS = {
  defaultStringType: "QUOTE_DOUBLE" as const,
};

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/config.yaml" || url.pathname === "/") {
      const token = url.searchParams.get("token") || request.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
      if (env.AUTH_TOKEN && token !== env.AUTH_TOKEN) {
        return new Response("Unauthorized", { status: 401 });
      }

      const subscriptionUrls = (env.SUBSCRIPTION_URLS || "")
        .split("\n")
        .map((s) => s.trim())
        .filter(Boolean);

      if (subscriptionUrls.length === 0) {
        return new Response("SUBSCRIPTION_URLS secret is not configured", { status: 500 });
      }

      let excludePattern: RegExp | null = null;
      if (env.EXCLUDE_PATTERN) {
        try {
          excludePattern = new RegExp(env.EXCLUDE_PATTERN);
        } catch (e) {
          return new Response(`Invalid EXCLUDE_PATTERN: ${e instanceof Error ? e.message : String(e)}`, { status: 400 });
        }
      }

      try {
        const results = await Promise.allSettled(
          subscriptionUrls.map((subUrl) => fetchSubscription(subUrl)),
        );

        const allProxies: ClashProxy[] = [];
        let failedCount = 0;
        for (const result of results) {
          if (result.status === "fulfilled") {
            allProxies.push(...result.value);
          } else {
            failedCount += 1;
            console.warn(`Subscription fetch failed: ${result.reason instanceof Error ? result.reason.message : String(result.reason)}`);
          }
        }

        let processed = allProxies;
        if (excludePattern) {
          processed = excludeByName(processed, excludePattern);
        }
        processed = dedupeByEndpoint(processed);
        processed = sortByName(processed);

        if (processed.length === 0) {
          return new Response(
            `No proxies available after parsing/filtering. subscriptions=${subscriptionUrls.length}, failed=${failedCount}, parsed=${allProxies.length}`,
            { status: 502 },
          );
        }

        const nodeNames = processed.map((p) => p.name);
        const proxyGroups = expandProxyGroups(nodeNames);

        const cleanProxies = processed.map(({ name, type, server, port, ...rest }) => {
          const obj: Record<string, unknown> = { name, type, server, port };
          for (const [k, v] of Object.entries(rest)) {
            if (v !== undefined && v !== null && v !== "") obj[k] = v;
          }
          return obj;
        });

        const config: Record<string, unknown> = {
          "mixed-port": TEMPLATE["mixed-port"] ?? 7890,
          "allow-lan": TEMPLATE["allow-lan"] ?? false,
          mode: TEMPLATE.mode ?? "rule",
          "log-level": TEMPLATE["log-level"] ?? "info",
          ...(TEMPLATE.dns ? { dns: TEMPLATE.dns } : {}),
          proxies: cleanProxies,
          "proxy-groups": proxyGroups,
          ...(TEMPLATE["rule-providers"] ? { "rule-providers": TEMPLATE["rule-providers"] } : {}),
          rules: (TEMPLATE.rules as string[])?.length ? TEMPLATE.rules : ["MATCH,🚀 节点选择"],
        };

        const header = `# Generated by clash-fusion\n# Nodes: ${processed.length}\n`;
        return new Response(header + stringify(config, YAML_STRINGIFY_OPTIONS), {
          headers: {
            "content-type": "text/yaml; charset=utf-8",
            "profile-update-interval": "6",
            "cache-control": "no-store",
          },
        });
      } catch (e) {
        return new Response(`Error: ${e instanceof Error ? e.message : String(e)}`, { status: 500 });
      }
    }

    return new Response("Not Found", { status: 404 });
  },
};

async function fetchSubscription(subUrl: string): Promise<ClashProxy[]> {
  const resp = await fetch(subUrl, {
    headers: { "user-agent": "clash-verge/2.0" },
    signal: AbortSignal.timeout(30000),
  });
  if (!resp.ok) {
    console.warn(`Failed ${subUrl.slice(0, 60)}: ${resp.status}`);
    return [];
  }
  const text = await resp.text();
  if (!text.trim()) return [];
  return parseSubscriptionContent(text);
}

function expandProxyGroups(nodeNames: string[]): Record<string, unknown>[] {
  const groups = TEMPLATE["proxy-groups"] as Array<Record<string, unknown>>;
  if (!Array.isArray(groups)) return [];
  return groups.map((group) => {
    const proxies = (group.proxies as string[] || []).flatMap((item) =>
      item === "$all" ? nodeNames : [item],
    );
    return { ...group, proxies: [...new Set(proxies)] };
  });
}
